name: fastpicker
description: This is an intuitive photo and video picker for FastAd. It supports multiple photos and videos selection on iOS and Android.
publish_to: 'none'
version: 1.0.0

environment:
  # sdk: '>=3.5.0 <4.0.0'
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  photo_manager: ^3.1.0
  photo_manager_image_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

